FROM node as base
WORKDIR /home/node/app

COPY package*.json ./

RUN npm i

COPY shared ./
COPY src ./
COPY extensions ./
COPY tsconfig.json ./


FROM base as build-shared
WORKDIR /home/node/app/shared

CMD npm run build


FROM build-shared as build
WORKDIR /home/node/app

CMD npm run build


FROM build as production
ENV NODE_PATH=./
CMD npx nodemon node_modules/directus/dist/start.js