version: "3.8"

services:
  postgres-db:
    container_name: postgres-db
    image: postgis/postgis:13-master
    volumes:
      - db-data:/var/lib/postgresql/data
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgrespw'
      POSTGRES_DB: 'directus'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes: 
  db-data: