FROM node:lts as base
WORKDIR /home/node/app

COPY ./shared ./shared
COPY ./src ./src
COPY ./extensions ./extensions
COPY ./schema-sync ./schema-sync

COPY *.json ./
COPY start.js ./

RUN npm i

FROM base as build-shared
WORKDIR /home/node/app/shared

CMD npm run build


FROM build-shared as build
WORKDIR /home/node/app

CMD npm run build

FROM node:lts-slim as production
WORKDIR /home/node/app
COPY --from=build /home/node/app .
ENV NODE_PATH=./
CMD node start.js