version: "3.8"

services:
  directus-app:
    image: directus-app
    build:
      context: .
      dockerfile: ./Dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
      - ./extensions:/home/node/app/extensions

      - ./.env:/home/node/app/.env
      - ./schema.yaml:/home/node/app/schema.yaml
    environment:
      NODE_ENV: development
    networks:
      - directus
    container_name: directus-app
    depends_on:
      postgres-db:
        condition: service_healthy
    ports:
      - "8080:8080"
      - "9229:9229"
    command:
      - /bin/sh
      - -c
      - |
        ./run_nodemon.sh

  postgres-db:
    container_name: postgres-db
    image: postgis/postgis:13-master
    volumes:
      - ./data/database:/var/lib/postgresql/data
    networks:
      - directus
    expose:
      - "5432"
    ports:
      - "5432:15432"
    environment:
      POSTGRES_USER: 'postgres-admin'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'directus-app'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    container_name: pg-admin
    image: dpage/pgadmin4
    restart: always
    networks:
      - directus
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

networks:
  directus:
