version: 1
directus: 9.20.4
collections:
  - collection: todo_items
    meta:
      accountability: all
      archive_app_filter: true
      archive_field: null
      archive_value: null
      collapse: open
      collection: todo_items
      color: null
      display_template: null
      group: todo_lists
      hidden: false
      icon: null
      item_duplication_fields: null
      note: null
      singleton: false
      sort: 1
      sort_field: null
      translations: null
      unarchive_value: null
    schema:
      comment: null
      name: todo_items
      schema: public
  - collection: todo_lists
    meta:
      accountability: all
      archive_app_filter: true
      archive_field: null
      archive_value: null
      collapse: open
      collection: todo_lists
      color: null
      display_template: null
      group: null
      hidden: false
      icon: null
      item_duplication_fields: null
      note: null
      singleton: false
      sort: 1
      sort_field: null
      translations: null
      unarchive_value: null
    schema:
      comment: null
      name: todo_lists
      schema: public
fields:
  - collection: todo_items
    field: date_created
    meta:
      collection: todo_items
      conditions: null
      display: datetime
      display_options:
        relative: true
      field: date_created
      group: null
      hidden: true
      interface: datetime
      note: null
      options: null
      readonly: true
      required: false
      sort: 6
      special:
        - date-created
      translations: null
      validation: null
      validation_message: null
      width: half
    schema:
      comment: null
      data_type: timestamp with time zone
      default_value: null
      foreign_key_column: null
      foreign_key_schema: null
      foreign_key_table: null
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: true
      is_primary_key: false
      is_unique: false
      max_length: null
      name: date_created
      numeric_precision: null
      numeric_scale: null
      schema: public
      table: todo_items
    type: timestamp
  - collection: todo_items
    field: id
    meta:
      collection: todo_items
      conditions: null
      display: null
      display_options: null
      field: id
      group: null
      hidden: true
      interface: input
      note: null
      options: null
      readonly: true
      required: false
      sort: 1
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      comment: null
      data_type: integer
      default_value: nextval('todo_items_id_seq'::regclass)
      foreign_key_column: null
      foreign_key_schema: null
      foreign_key_table: null
      generation_expression: null
      has_auto_increment: true
      is_generated: false
      is_nullable: false
      is_primary_key: true
      is_unique: true
      max_length: null
      name: id
      numeric_precision: 32
      numeric_scale: 0
      schema: public
      table: todo_items
    type: integer
  - collection: todo_items
    field: is_done
    meta:
      collection: todo_items
      conditions: null
      display: null
      display_options: null
      field: is_done
      group: null
      hidden: false
      interface: boolean
      note: null
      options:
        label: is done
      readonly: false
      required: true
      sort: 3
      special:
        - cast-boolean
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      comment: null
      data_type: boolean
      default_value: false
      foreign_key_column: null
      foreign_key_schema: null
      foreign_key_table: null
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: true
      is_primary_key: false
      is_unique: false
      max_length: null
      name: is_done
      numeric_precision: null
      numeric_scale: null
      schema: public
      table: todo_items
    type: boolean
  - collection: todo_items
    field: list_id
    meta:
      collection: todo_items
      conditions: null
      display: null
      display_options: null
      field: list_id
      group: null
      hidden: false
      interface: select-dropdown-m2o
      note: null
      options:
        template: '{{name}}'
      readonly: false
      required: true
      sort: 4
      special:
        - m2o
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      comment: null
      data_type: uuid
      default_value: null
      foreign_key_column: id
      foreign_key_schema: public
      foreign_key_table: todo_lists
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: true
      is_primary_key: false
      is_unique: false
      max_length: null
      name: list_id
      numeric_precision: null
      numeric_scale: null
      schema: public
      table: todo_items
    type: uuid
  - collection: todo_items
    field: text
    meta:
      collection: todo_items
      conditions: null
      display: null
      display_options: null
      field: text
      group: null
      hidden: false
      interface: input
      note: null
      options: null
      readonly: false
      required: true
      sort: 2
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      comment: null
      data_type: character varying
      default_value: null
      foreign_key_column: null
      foreign_key_schema: null
      foreign_key_table: null
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: true
      is_primary_key: false
      is_unique: false
      max_length: 255
      name: text
      numeric_precision: null
      numeric_scale: null
      schema: public
      table: todo_items
    type: string
  - collection: todo_items
    field: user_created
    meta:
      collection: todo_items
      conditions: null
      display: user
      display_options: null
      field: user_created
      group: null
      hidden: true
      interface: select-dropdown-m2o
      note: null
      options:
        template: '{{avatar.$thumbnail}} {{first_name}} {{last_name}}'
      readonly: true
      required: false
      sort: 5
      special:
        - user-created
      translations: null
      validation: null
      validation_message: null
      width: half
    schema:
      comment: null
      data_type: uuid
      default_value: null
      foreign_key_column: id
      foreign_key_schema: public
      foreign_key_table: directus_users
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: true
      is_primary_key: false
      is_unique: false
      max_length: null
      name: user_created
      numeric_precision: null
      numeric_scale: null
      schema: public
      table: todo_items
    type: uuid
  - collection: todo_lists
    field: date_created
    meta:
      collection: todo_lists
      conditions: null
      display: datetime
      display_options:
        relative: true
      field: date_created
      group: null
      hidden: true
      interface: datetime
      note: null
      options: null
      readonly: true
      required: false
      sort: 4
      special:
        - date-created
      translations: null
      validation: null
      validation_message: null
      width: half
    schema:
      comment: null
      data_type: timestamp with time zone
      default_value: null
      foreign_key_column: null
      foreign_key_schema: null
      foreign_key_table: null
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: true
      is_primary_key: false
      is_unique: false
      max_length: null
      name: date_created
      numeric_precision: null
      numeric_scale: null
      schema: public
      table: todo_lists
    type: timestamp
  - collection: todo_lists
    field: id
    meta:
      collection: todo_lists
      conditions: null
      display: null
      display_options: null
      field: id
      group: null
      hidden: true
      interface: input
      note: null
      options: null
      readonly: true
      required: false
      sort: 1
      special:
        - uuid
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      comment: null
      data_type: uuid
      default_value: null
      foreign_key_column: null
      foreign_key_schema: null
      foreign_key_table: null
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: false
      is_primary_key: true
      is_unique: true
      max_length: null
      name: id
      numeric_precision: null
      numeric_scale: null
      schema: public
      table: todo_lists
    type: uuid
  - collection: todo_lists
    field: name
    meta:
      collection: todo_lists
      conditions: null
      display: null
      display_options: null
      field: name
      group: null
      hidden: false
      interface: input
      note: null
      options: null
      readonly: false
      required: true
      sort: 2
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      comment: null
      data_type: character varying
      default_value: null
      foreign_key_column: null
      foreign_key_schema: null
      foreign_key_table: null
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: true
      is_primary_key: false
      is_unique: false
      max_length: 255
      name: name
      numeric_precision: null
      numeric_scale: null
      schema: public
      table: todo_lists
    type: string
  - collection: todo_lists
    field: user_created
    meta:
      collection: todo_lists
      conditions: null
      display: user
      display_options: null
      field: user_created
      group: null
      hidden: true
      interface: select-dropdown-m2o
      note: null
      options:
        template: '{{avatar.$thumbnail}} {{first_name}} {{last_name}}'
      readonly: true
      required: false
      sort: 3
      special:
        - user-created
      translations: null
      validation: null
      validation_message: null
      width: half
    schema:
      comment: null
      data_type: uuid
      default_value: null
      foreign_key_column: id
      foreign_key_schema: public
      foreign_key_table: directus_users
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: true
      is_primary_key: false
      is_unique: false
      max_length: null
      name: user_created
      numeric_precision: null
      numeric_scale: null
      schema: public
      table: todo_lists
    type: uuid
relations:
  - collection: todo_items
    field: list_id
    meta:
      junction_field: null
      many_collection: todo_items
      many_field: list_id
      one_allowed_collections: null
      one_collection: todo_lists
      one_collection_field: null
      one_deselect_action: nullify
      one_field: null
      sort_field: null
    related_collection: todo_lists
    schema:
      column: list_id
      constraint_name: todo_items_list_id_foreign
      foreign_key_column: id
      foreign_key_schema: public
      foreign_key_table: todo_lists
      on_delete: SET NULL
      on_update: NO ACTION
      table: todo_items
  - collection: todo_items
    field: user_created
    meta:
      junction_field: null
      many_collection: todo_items
      many_field: user_created
      one_allowed_collections: null
      one_collection: directus_users
      one_collection_field: null
      one_deselect_action: nullify
      one_field: null
      sort_field: null
    related_collection: directus_users
    schema:
      column: user_created
      constraint_name: todo_items_user_created_foreign
      foreign_key_column: id
      foreign_key_schema: public
      foreign_key_table: directus_users
      on_delete: NO ACTION
      on_update: NO ACTION
      table: todo_items
  - collection: todo_lists
    field: user_created
    meta:
      junction_field: null
      many_collection: todo_lists
      many_field: user_created
      one_allowed_collections: null
      one_collection: directus_users
      one_collection_field: null
      one_deselect_action: nullify
      one_field: null
      sort_field: null
    related_collection: directus_users
    schema:
      column: user_created
      constraint_name: todo_lists_user_created_foreign
      foreign_key_column: id
      foreign_key_schema: public
      foreign_key_table: directus_users
      on_delete: NO ACTION
      on_update: NO ACTION
      table: todo_lists
